name: leanix-action-test

on:
  workflow_dispatch:

  
env:
  HOST: app.leanix.net
  LEANIX_MANIFEST_PATH: /lx-manifest.yml
  DEPENDENCY_MANAGER: MAVEN
  STAGE: test
  VERSION: 2.2.0
  ALLOW_FAILURE: false

jobs:
  leanix_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: LeanIX Microservice Intelligence
        uses: leanix/github-actions-store-leanix-plugin@feature/CID-477/add-custom-user-settings-support-for-maven
        id: LIXMI
        with:
          host: ${{ env.HOST }}
          api-token: ${{ secrets.LEANIX_API_TOKEN }}
          manifest-path: ${{ env.LEANIX_MANIFEST_PATH }}
          dependency-manager: ${{ env.DEPENDENCY_MANAGER }}
          maven-user-settings-path: /settings.xml
          stage: ${{ env.STAGE }}
          version: ${{ env.VERSION }}
          allow-failure: ${{ env.ALLOW_FAILURE }}
